#!/bin/bash
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# homesbrew
bash ${BASEDIR}/.homebrew/install.sh
# osx
bash ${BASEDIR}/.osx/set-defaults.sh
# python
bash ${BASEDIR}/.python/install.sh
# zsh
ln -s ${BASEDIR}/.zshrc ~/.zshrc
# aws
ln -s ${BASEDIR}/.aws/config ~/.aws/config
