#!/bin/bash
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# ntp.br
sudo bash ${BASEDIR}/.ntp/install.sh
# homesbrew
bash ${BASEDIR}/.homebrew/install.sh
# python
bash ${BASEDIR}/.python/install.sh
# atom
ln -s ${BASEDIR}/.atom.symlink ~/.atom
# vimfiles
ln -s ${BASEDIR}/.vimfiles/.vimrc ~/.vimrc
# osx
bash ${BASEDIR}/.osx/set-defaults.sh
# Powerline
bash ${BASEDIR}/.powerline/install.sh
# iTerm2
rm ~/Library/Preferences/com.googlecode.iterm2.plist
ln -s ${BASEDIR}/.iterm2/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist
# zsh
bash ${BASEDIR}/.zshrc/install.sh
rm ~/.zshrc
ln -s ${BASEDIR}/.zshrc/.zshrc ~/.zshrc
