# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # config.gui = true

  # Ubuntu vivid64 configuration
  config.vm.define "ubuntu" do |ubuntu_config|
    ubuntu_config.vm.box = "ubuntu/trusty64" # to delete: 'vagrant destroy; box remove coreos-box'
    ubuntu_config.vm.network "private_network", ip: "192.168.33.10"
    #ubuntu_config.vm.network "public_network", bridge: [
    #  "en1: Wi-Fi (AirPort)",
    #  "en4: USB Ethernet",
    #]
    ubuntu_config.vm.network "public_network", ip: "192.168.0.16" 
#    ubuntu_config.vm.synced_folder "/Users/vitor/Projects/", "/home/vagrant/projects"
#    ubuntu_config.vm.synced_folder "/Users/vitor/Drive/Mestrado/Disciplinas/processamento-de-alto-desempenho/", "/home/vagrant/pad/"
#    ubuntu_config.vm.synced_folder "/Users/vitor/Pictures/311015-peroba/", "/home/vagrant/311015-peroba"

    ubuntu_config.vm.provider :virtualbox do |vb| 
    	vb.customize ["modifyvm", :id, "--memory",  "2048"]
    	vb.customize ["modifyvm", :id, "--cpus", "2"] 
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
  # End ubuntu configuration

  # Windows 7 Modern.ie configuration
  config.vm.define "win7" do |win7_config|
    win7_config.vm.box = "modern.ie/win7-ie11"
    win7_config.vm.box_url = "http://aka.ms/vagrant-win7-ie11"
    win7_config.vm.boot_timeout = 500
    win7_config.vm.network "private_network", ip: "192.168.33.11"
    win7_config.vm.network "forwarded_port", guest: 3389, host: 3389, id: "rdp", auto_correct: true
    win7_config.vm.communicator = "winrm"
    win7_config.winrm.username = "IEUser"
    win7_config.winrm.password = "Passw0rd!"
    #win7_config.vm.network "public_network", bridge: [
      # "en1: Wi-Fi (AirPort)",
    #  "en4: USB Ethernet",
    #]

    win7_config.vm.synced_folder "/Users/vitor/Projects/", "/projects"
    win7_config.vm.synced_folder "/Users/vitor/Games/", "/games"
    win7_config.vm.synced_folder "/Users/vitor/Drive/Cotidiano/protocolo-servicos-de-redes/", "/protocolo-servicos-de-rede"

    win7_config.vm.provider "virtualbox" do |vb| 
      vb.gui = true # enable for first run
    	vb.customize ["modifyvm", :id, "--memory",  "2048"]
      vb.customize ["modifyvm", :id, "--vram", "128"]
    	vb.customize ["modifyvm", :id, "--cpus", "2"] 
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
    end
  end
  # End win7 configuration
end
