"Charset Config"
scriptencoding utf-8
set encoding=utf-8
set nocompatible
filetype off

"General Config"
set number
set backspace=indent,eol,start
set showmode
set visualbell
set hlsearch
set laststatus=2
syntax on
filetype plugin on
"color dracula

"Turn Off Swap Files"
set noswapfile
set nobackup
set nowb

"Indentation Config"
set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set showmatch

"Scrolling Config"
set scrolloff=8
set sidescrolloff=15
set sidescroll=1

"Changing make options"
augroup auto_make
    autocmd!
    "autocmd BufWritePost * silent make
    autocmd QuickFixCmdPost *make* cwindow
augroup END

"Source files"
source ~/.vim/vundle.vim
source ~/.vim/plugins.vim
